#ifndef CHANNELCLIENTSTATUS_HPP
# define CHANNELCLIENTSTATUS_HPP

enum ChannelClientStatus {
	CHANNEL_OK,
	CHANNEL_NOT_ENOUGH_PLACES,
	CHANNEL_INVALID_KEY,
	CHANNEL_CLIENT_NOT_INVITED,
	CHANNEL_CLIENT_ALREADY_IN
};

#endif